(function() {var implementors = {};
implementors["byteorder"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"enum\" href=\"byteorder/enum.BigEndian.html\" title=\"enum byteorder::BigEndian\">BigEndian</a>",synthetic:false,types:["byteorder::BigEndian"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"enum\" href=\"byteorder/enum.LittleEndian.html\" title=\"enum byteorder::LittleEndian\">LittleEndian</a>",synthetic:false,types:["byteorder::LittleEndian"]},];
implementors["cssparser"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"cssparser/struct.SourcePosition.html\" title=\"struct cssparser::SourcePosition\">SourcePosition</a>",synthetic:false,types:["cssparser::tokenizer::SourcePosition"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"cssparser/struct.CowRcStr.html\" title=\"struct cssparser::CowRcStr\">CowRcStr</a>&lt;'a&gt;",synthetic:false,types:["cssparser::cow_rc_str::CowRcStr"]},];
implementors["futf"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"enum\" href=\"futf/enum.Meaning.html\" title=\"enum futf::Meaning\">Meaning</a>",synthetic:false,types:["futf::Meaning"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"futf/struct.Codepoint.html\" title=\"struct futf::Codepoint\">Codepoint</a>&lt;'a&gt;",synthetic:false,types:["futf::Codepoint"]},];
implementors["html5ever"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"enum\" href=\"html5ever/tokenizer/states/enum.ScriptEscapeKind.html\" title=\"enum html5ever::tokenizer::states::ScriptEscapeKind\">ScriptEscapeKind</a>",synthetic:false,types:["html5ever::tokenizer::states::ScriptEscapeKind"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"enum\" href=\"html5ever/tokenizer/states/enum.DoctypeIdKind.html\" title=\"enum html5ever::tokenizer::states::DoctypeIdKind\">DoctypeIdKind</a>",synthetic:false,types:["html5ever::tokenizer::states::DoctypeIdKind"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"enum\" href=\"html5ever/tokenizer/states/enum.RawKind.html\" title=\"enum html5ever::tokenizer::states::RawKind\">RawKind</a>",synthetic:false,types:["html5ever::tokenizer::states::RawKind"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"enum\" href=\"html5ever/tokenizer/states/enum.AttrValueKind.html\" title=\"enum html5ever::tokenizer::states::AttrValueKind\">AttrValueKind</a>",synthetic:false,types:["html5ever::tokenizer::states::AttrValueKind"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"enum\" href=\"html5ever/tokenizer/states/enum.State.html\" title=\"enum html5ever::tokenizer::states::State\">State</a>",synthetic:false,types:["html5ever::tokenizer::states::State"]},];
implementors["kuchiki"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"kuchiki/struct.ExpandedName.html\" title=\"struct kuchiki::ExpandedName\">ExpandedName</a>",synthetic:false,types:["kuchiki::attributes::ExpandedName"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"kuchiki/struct.Specificity.html\" title=\"struct kuchiki::Specificity\">Specificity</a>",synthetic:false,types:["kuchiki::select::Specificity"]},];
implementors["log"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"enum\" href=\"log/enum.Level.html\" title=\"enum log::Level\">Level</a>",synthetic:false,types:["log::Level"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"enum\" href=\"log/enum.LevelFilter.html\" title=\"enum log::LevelFilter\">LevelFilter</a>",synthetic:false,types:["log::LevelFilter"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"log/struct.Metadata.html\" title=\"struct log::Metadata\">Metadata</a>&lt;'a&gt;",synthetic:false,types:["log::Metadata"]},{text:"impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"log/struct.MetadataBuilder.html\" title=\"struct log::MetadataBuilder\">MetadataBuilder</a>&lt;'a&gt;",synthetic:false,types:["log::MetadataBuilder"]},];
implementors["markup5ever"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"markup5ever/interface/struct.QualName.html\" title=\"struct markup5ever::interface::QualName\">QualName</a>",synthetic:false,types:["markup5ever::interface::QualName"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"markup5ever/interface/struct.Attribute.html\" title=\"struct markup5ever::interface::Attribute\">Attribute</a>",synthetic:false,types:["markup5ever::interface::Attribute"]},];
implementors["proc_macro2"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"proc_macro2/struct.Ident.html\" title=\"struct proc_macro2::Ident\">Ident</a>",synthetic:false,types:["proc_macro2::Ident"]},];
implementors["selectors"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"selectors/matching/struct.ElementSelectorFlags.html\" title=\"struct selectors::matching::ElementSelectorFlags\">ElementSelectorFlags</a>",synthetic:false,types:["selectors::matching::ElementSelectorFlags"]},];
implementors["servo_arc"] = [{text:"impl&lt;T:&nbsp;?<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sized.html\" title=\"trait core::marker::Sized\">Sized</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"servo_arc/struct.Arc.html\" title=\"struct servo_arc::Arc\">Arc</a>&lt;T&gt;",synthetic:false,types:["servo_arc::Arc"]},];
implementors["smallvec"] = [{text:"impl&lt;A:&nbsp;<a class=\"trait\" href=\"smallvec/trait.Array.html\" title=\"trait smallvec::Array\">Array</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"smallvec/struct.SmallVec.html\" title=\"struct smallvec::SmallVec\">SmallVec</a>&lt;A&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;A::<a class=\"type\" href=\"smallvec/trait.Array.html#associatedtype.Item\" title=\"type smallvec::Array::Item\">Item</a>: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a>,&nbsp;</span>",synthetic:false,types:["smallvec::SmallVec"]},];
implementors["string_cache"] = [{text:"impl&lt;Static:&nbsp;<a class=\"trait\" href=\"string_cache/atom/trait.StaticAtomSet.html\" title=\"trait string_cache::atom::StaticAtomSet\">StaticAtomSet</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"string_cache/atom/struct.Atom.html\" title=\"struct string_cache::atom::Atom\">Atom</a>&lt;Static&gt;",synthetic:false,types:["string_cache::atom::Atom"]},];
implementors["syn"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"syn/struct.Lifetime.html\" title=\"struct syn::Lifetime\">Lifetime</a>",synthetic:false,types:["syn::lifetime::Lifetime"]},];
implementors["tendril"] = [{text:"impl&lt;F, A&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a> for <a class=\"struct\" href=\"tendril/struct.Tendril.html\" title=\"struct tendril::Tendril\">Tendril</a>&lt;F, A&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;F: <a class=\"trait\" href=\"tendril/fmt/trait.SliceFormat.html\" title=\"trait tendril::fmt::SliceFormat\">SliceFormat</a>,<br>&nbsp;&nbsp;&nbsp;&nbsp;&lt;F as <a class=\"trait\" href=\"tendril/fmt/trait.SliceFormat.html\" title=\"trait tendril::fmt::SliceFormat\">SliceFormat</a>&gt;::<a class=\"type\" href=\"tendril/fmt/trait.SliceFormat.html#associatedtype.Slice\" title=\"type tendril::fmt::SliceFormat::Slice\">Slice</a>: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/cmp/trait.Ord.html\" title=\"trait core::cmp::Ord\">Ord</a>,<br>&nbsp;&nbsp;&nbsp;&nbsp;A: <a class=\"trait\" href=\"tendril/trait.Atomicity.html\" title=\"trait tendril::Atomicity\">Atomicity</a>,&nbsp;</span>",synthetic:false,types:["tendril::tendril::Tendril"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
